### ISSUE TITLE
Julia version path

### ISSUE THREAD

**Issue by asikstel** [gdkrmr/lsp-julia#12]
Hi, 
with Julia 1.1 (which is the current stable) this package does not work since cannot connect to the LSP server. However if I change the line 
from
`(defcustom lsp-julia-default-environment "~/.julia/environments/v1.0"`
to
`(defcustom lsp-julia-default-environment "~/.julia/environments/v1.1"` 
works flawlessly. Maybe the version should be checked automatically.

**Comment by non-Jedi** [comment]
I think allowing that variable to be customized works well enough for the purposes of this package. That said, we should certainly bump the default version up to 1.1. Feel free to submit a pull-request doing so. :)

**Comment by asikstel** [comment]
Ah sorry, I didn't check if its customizable 🤦‍♂️ 
Cheers! Thanks for the great package.
