### ISSUE TITLE
Getting documentation for functions not from base?

### ISSUE THREAD

**Issue by leafpile** [gdkrmr/lsp-julia#15]
I'm wondering if there's a way for `lsp-describe-thing-at-point` to work for functions from, say, `LinearAlgebra` package?

Currently if I call the command on `diag` I would get an empty buffer.

**Comment by non-Jedi** [comment]
Needs https://github.com/julia-vscode/LanguageServer.jl/issues/268 fixed

**Comment by non-Jedi** [comment]
Actually with eglot, docs work for me for both standard library functions and from e.g. `LinearAlgebra` as well as any other package. I don't currently have lsp-julia installed, so I can't easily test there. @gdkrmr, is this the behavior you see with lsp?

**Comment by gdkrmr** [comment]
You are right I cannot figure out how to see the documentation for these functions. If I move my cursor over a function I get:
- Either a list with methods or the examples in the minibuffer, which I don't really find useful, it just messes up the layout by enlarging the minibuffer.
- A somewhat annoying popup buffer in the upper right corner with the the documentation (not always the documentation of the right method).
- I don't get any documentation for functions that are declared in other packages. 

In general I think that the documentation part in `lsp-julia` doesn't really work well. I mostly use it for linting and jumping to definitions. This is really not ideal but I am not sure if `lsp-julia` can do much about this, I guess this would be more the job of `lsp-mode` and co to fix the UI annoyances.

In VSCode I actually get documentation for methods from other packages I mouse over a method. 
I just saw that VSCode uses a newer version of `SymbolServer`, I should probably update that and see if it helps.

**Comment by non-Jedi** [comment]
@gdkrmr well if you can't get this figured out, I've finally got a good answer for your question about why I prefer eglot.

**Comment by gdkrmr** [comment]
Is this fixed
