### ISSUE TITLE
Maintain single repo for lsp-julia

### ISSUE THREAD

**Issue by ghost** [gdkrmr/lsp-julia#26]
I can see two forks of lsp-julia 
- https://github.com/non-Jedi/lsp-julia 
- https://github.com/gdkrmr/lsp-julia
As a user of lsp-julia, I would like to see efforts going in to anyone of these two for the following reasons. 
- Different versions of Dependent packages though they are self contained
- toggling between these two forks is very cumbersome
- I guess we can take one step at a time to sort out things on lsp (emacs side) or on LanguageServer.jl side (though efforts are made to be in consistent with VSCode) a steady progress can be made.

These are just my opinions , compaed to other editors Emacs is getting less support from community. Though we can stay lean and small we can try to be helpful and help each other.

**Comment by gdkrmr** [comment]
If you are referring to lsp-julia currently not working with Julia 1.4, this seems to be a miscommunication between `lsp-mode` and `LanguageServer.jl`, please see the linked issues in #20.

> These are just my opinions , compaed to other editors Emacs is getting less support from community. Though we can stay lean and small we can try to be helpful and help each other.

PRs are welcome :-)

The original repo is https://github.com/MartinWolke/lsp-julia all the others are forks. I use https://github.com/gdkrmr/lsp-julia as my personal develop repo and as soon as there is something worth publishing, I merge it into this repo. This repo is the one used on melpa for historical reasons, even though the owner is not using `lsp-mode`.

> toggling between these two forks is very cumbersome

Easy switching between repos is super simple with quelpa (reading the documentation is recommended):
```
(quelpa
     '(lsp-julia :fetcher github
                                  :repo "gdkrmr/lsp-julia"
                                  ;; :repo "AlexLewandowski/lsp-julia"
                                  ;; :repo "non-Jedi/lsp-julia"
                                  :files (:defaults "languageserver")))
```
