### ISSUE TITLE
Cannot start LanguageServer when installed from quelpa

### ISSUE THREAD

**Issue by prassee** [gdkrmr/lsp-julia#27]
I'm using Julia 1.3.1 , as an attempt to install lsp-julia I followed  the README  and installed via quelpa. Below is my config

```
(quelpa '(lsp-julia :fetcher github
                    :repo "non-Jedi/lsp-julia"
                    :files (:defaults "languageserver")
                    ))
(setq lsp-julia-default-environment "~/.julia/environments/v1.3")
(require 'lsp-julia)
```
However when started lang.server by `M-x lsp` command it failed and  got the following error on `julia-ls::stderr` buffer.
I guess with the above config I should be using the LanguageServer as bundled in this git repo. 

```
ERROR: MethodError: no method matching Union{Int64, String}(::String)
Stacktrace:
 [1] LanguageServer.InitializeParams(::Dict{String,Any}) at /home/saipranav/.emacs.d/lisp/languageserver/LanguageServer/src/protocol/initialize.jl:111
 [2] parse_params(::Type{Val{:initialize}}, ::Dict{String,Any}) at /home/saipranav/.emacs.d/lisp/languageserver/LanguageServer/src/requests/init.jl:123
 [3] parse(::Type{LanguageServer.JSONRPC.Request}, ::Dict{String,Any}) at /home/saipranav/.emacs.d/lisp/languageserver/LanguageServer/src/jsonrpc.jl:46
 [4] run(::LanguageServerInstance) at /home/saipranav/.emacs.d/lisp/languageserver/LanguageServer/src/languageserverinstance.jl:236
 [5] top-level scope at none:1

Process julia-ls stderr finished
```

**Comment by gdkrmr** [comment]
try to not set `lsp-julia-default-environment`. Are you sure that the package from the right repo is installed?

**Comment by prassee** [comment]
> try to not set `lsp-julia-default-environment`. Are you sure that the 


package from the right repo is installed?
does that mean the `:repo`  
if so I set that to non-Jedi/lsp-julia. Please clarify what that means otherwise.

Also got the same error even after not setting the 
`lsp-julia-default-environment`

**Comment by gdkrmr** [comment]
I get the reported error when I use Julia 1.4 and current master on the `"gdkrmr/lsp-julia"` repo (see https://github.com/julia-vscode/LanguageServer.jl/issues/651). I do not get any errors when using Julia 1.3 and master of this repo. master of this repo does not currently work with Julia 1.4.

**Comment by ghost** [comment]
I had both 1.3 and 1.4 versions of Julia installed, after doing a complete removal of both plus deleting `~/.julia` and re-install of 1.3.1. I got this working. @gdkrmr  Thanks for guiding me and I would say we can close this issue

**Comment by gdkrmr** [comment]
glad to help
