### ISSUE TITLE
README uses removed function of PackageCompiler

### ISSUE THREAD

**Issue by juanscr** [gdkrmr/lsp-julia#41]
As stated in the [PackageCompiler Documentation](https://julialang.github.io/PackageCompiler.jl/dev/upgrade/), the 1.0 version of PackageCompiler made significant changes to previous versions.

In this manner, the function `compile_package` is not longer used for versions of PackageCompiler superior or equal to 1.0. I would suggest updating the README using the updated function `create_sysimage` or removing it entirely to not create any misunderstandings.

I think a correct replacement for the README would be something like:
```
julia> Pkg.add("PackageCompiler")
julia> using PackageCompiler
julia> create_sysimage(:LanguageServer, sysimage_path="languageserver.so")

**Comment by juanscr** [comment]
If someone is wondering how to use the created system image add this to your Emacs config file:
```
;; Use global server
(setq lsp-julia-package-dir nil)

;; Add system image
(setq lsp-julia-flags `("-J/path/to/languageserver.so"))
```

**Comment by gdkrmr** [comment]
Thanks

**Comment by matianhe3** [comment]
```
create_sysimage(:LanguageServer, sysimage_path="/Users/matianhe/.config/julia/compiled/languageserver.so")
```

```
(use-package lsp-julia
  :config
  (setq lsp-julia-package-dir nil
        lsp-julia-flags `("-J/Users/matianhe/.config/julia/compiled/languageserver.so")
        lsp-julia-default-environment "~/.config/julia/environments/v1.6"
        lsp-julia-default-depot "~/.config/julia/")
  :hook ((julia-mode . (lambda () (require 'lsp-julia)))
         (julia-mode . lsp-deferred)))
```

it's right? it not work for me.

**Comment by juanscr** [comment]
@matianhe3 what error do you get? 

Have you tried running it in a terminal? Something like: `julia -J/Users/matianhe/.config/julia/compiled/languageserver.so` to see if it at least works out in the terminal.
