### ISSUE TITLE
Variable completion candidates always show the type Enum

### ISSUE THREAD

**Issue by dmalyuta** [gdkrmr/lsp-julia#43]
I don't know whether this is an `lsp-julia` or a `LanguageServer.jl` issue. My first attempt is to post here. First of all, I am using:

- Emacs: GNU Emacs 27.1.90
- OS: Ubuntu 20.04.1 LTS
- Julia: 1.5.3
- LanguageServer.jl: [2b0e0bc5] LanguageServer v3.2.1-DEV `https://github.com/julia-vscode/LanguageServer.jl#master`
- SymbolServer.jl: [cf896787] SymbolServer v6.0.1

The issue that I'm seeing is that while variable completion candidates show up (for structs, workspace variables, etc.), they are always labelled as having the type "Enum". But I have specified the variable type, as you can see in the example below, so I feel like it should be possible for LSP to retrieve and show that information? Any help is very much appreciated on this matter, because it is annoying to have to jump to the variable definition in order to check its type.

![image](https://user-images.githubusercontent.com/12475811/106040500-6968d580-608f-11eb-81cf-a05c1ad12c10.png)

**Comment by gdkrmr** [comment]
Have you asked the `LanguageServer.jl` guys?. I don't think that `lsp-julia` can do anything about this.

**Comment by dmalyuta** [comment]
It was my next step, pending comments by you guys on here - I'll do that now.

**Comment by gdkrmr** [comment]
Have you checked, if the same happens in VSCode?

**Comment by dmalyuta** [comment]
It seems like VSCode also does not report the variable types directly. However, there is an option to preview the line on which the variable is defined in a mini-window using VSCode's GUI. This indicates to me that perhaps the feature is not there, otherwise I would expect the variable types to be written directly next to the variable in the completion dropdown menu.
