### ISSUE TITLE
[noob] can you give me the completed configure code ?

### ISSUE THREAD

**Issue by kurt-steiner** [gdkrmr/lsp-julia#47]
I don't know which part is wrong,  
1. I install the `LanguageServer` from REPL
2. write the configure code in `init.el`

after evaluate them
```emacs-lisp
(use-package lsp-julia
  :config
  (setq lsp-julia-default-environment "~/.julia/environments/v1.5"))
```
I was told that,   
> Error (use-package): Cannot load lsp-julia  

I have been confused now, can you give me some help.

**Comment by gdkrmr** [comment]
what version of julia do you have installed?

**Comment by kurt-steiner** [comment]
1.5

**Comment by gdkrmr** [comment]
Not sure, have you tried reinstalling?

**Comment by fvanmaele** [comment]
I can't get the instructions to work either. I've installed lsp-julia from MELPA, compiled a `languageserver.so` with `PackageCompiler`:
```julia
julia> create_sysimage(:LanguageServer, sysimage_path="/home/fvanmaele/.julia/languageserver.so")
[ Info: PackageCompiler: creating system image object file, this might take a while...
```
My ~/.emacs
```lisp

(setq lsp-julia-package-dir nil)
(setq lsp-julia-flags `("-J/home/fvanmaele/.julia/languageserver.so"))
(require 'lsp-julia)
```

Enabling `lsp-mode` in a `julia-mode` buffer only gives `Julia LSP[Disconnected]`. I use Julia version 1.7.

edit: I solved by running `lsp` and then importing the directory of my `.jl` file with `.`.
