### ISSUE TITLE
Missing reference: LinearAlgebra

### ISSUE THREAD

**Issue by bojohnson5** [gdkrmr/lsp-julia#52]
I have a new install of the julia layer in Spacemacs and a fresh install of Julia 1.6.1 on macOS 11.4. I've added
```
(julia :variables
       julia-backend 'lsp)
```
to my dotspacemacs/layers and 
```
(setq lsp-julia-default-environment "~/.julia/environments/v1.6")
```
to my dotspacemacs/user-config. I created a test file called `test_julia.jl` and it consists of
```
using LinearAlgebra

x = 1:0.01:10
y = sin.(x)
```
and I get a flycheck error saying "Missing reference: LinearAlgebra [Julia]". I'm thinking I missed something from the docs or installation instructions, but how do I fix this error and have lsp find the right modules included with Julia? For some more reference, I don't get an error when I do something like `import Base`. It seems to only be with standard library modules.

**Comment by bojohnson5** [comment]
> I have a new install of the julia layer in Spacemacs and a fresh install of Julia 1.6.1 on macOS 11.4. I've added
> 
> ```
> (julia :variables
>        julia-backend 'lsp)
> ```
> 
> to my dotspacemacs/layers and
> 
> ```
> (setq lsp-julia-default-environment "~/.julia/environments/v1.6")
> ```
> 
> to my dotspacemacs/user-config. I created a test file called `test_julia.jl` and it consists of
> 
> ```
> using LinearAlgebra
> 
> x = 1:0.01:10
> y = sin.(x)
> ```
> 
> and I get a flycheck error saying "Missing reference: LinearAlgebra [Julia]". I'm thinking I missed something from the docs or installation instructions, but how do I fix this error and have lsp find the right modules included with Julia? For some more reference, I don't get an error when I do something like `import Base`. It seems to only be with standard library modules.

**Comment by bojohnson5** [comment]
Saw something similar with LanguageServer.jl and posted there
https://github.com/julia-vscode/LanguageServer.jl/issues/960#issuecomment-880932803

**Comment by bojohnson5** [comment]
Inadvertently closed the issue.

**Comment by gdkrmr** [comment]
I don't think we can do anything about this here, you have to ask the maintainers of `LanguageServer.jl`
