### ISSUE TITLE
The connected server(s) does not support method textDocument/hover

### ISSUE THREAD

**Issue by fleimgruber** [gdkrmr/lsp-julia#53]
lsp-julia 20210530.2152
Julia 1.5
Windows 10
Emacs 27.2

I am using the bundled LanguageServer, i.e. `lsp-julia-package-dir` is `~/.emacs.d/elpa/27.2/develop/lsp-julia-20210530.2152/languageserver`.
When in a Julia file, since I get no help on a function under point, I explicitly call `lsp-ui-doc-show` and get the error:

```
helm-M-x-execute-command: The connected server(s) does not support method textDocument/hover.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section
```

When I do `lsp-describe-session` I get the relevant section

```
 `-[-] julia-ls:11476/starting
    |-[-] Buffers
    |  `-[+] pendulum.jl
    `-[+] Capabilities
```

and Capabilities section is empty. Any hints for debugging further?

**Comment by fleimgruber** [comment]
Sorry for the noise, it was right there: `julia-ls:11476/starting` ... after a while the `/starting` part disappears and everything works smoothly.

**Comment by gdkrmr** [comment]
I guess this was precompilation...
