### ISSUE TITLE
Transfer repo to @gdkrmr

### ISSUE THREAD

**Issue by non-Jedi** [gdkrmr/lsp-julia#59]
Hi @gdkrmr. It's up to you, but I'd be happy to transfer this repo's ownership to you if you'd like. I won't be creating another repo named "lsp-julia", so the redirects from non-jedi/lsp-julia should keep working for the foreseeable future. Also happy to leave it where it is if that's your preference, but it seems like you might want the "credit" of having it under your username since you're the one doing all the work on it now.

Let me know if you want me to transfer, and if you do, you'll have to delete the existing repo at gdkrmr/lsp-julia before I can start the transfer process.

**Comment by gdkrmr** [comment]
Would that change the url of the repo?

**Comment by non-Jedi** [comment]
Yes. But github.com/non-jedi/lsp-julia would transparently redirect to github.com/gdkrmr/lsp-julia; both for http(s) and for ssh.

**Comment by gdkrmr** [comment]
ok, i am all for it, thanks! Let me know if I have to delete my fork first.

**Comment by non-Jedi** [comment]
Yep. Let me know by pinging me here once your fork is deleted or renamed, and I'll push the transfer button. After that, you'll get an email and have 24 hours to accept the transfer.

**Comment by gdkrmr** [comment]
deleted

**Comment by non-Jedi** [comment]
Great! Should probably go ahead and update the URL in melpa and in places like the LanguageServer.jl wiki just to be safe.

**Comment by gdkrmr** [comment]
done, thanks! Should I also remove you from the maintainers list? I'll keep you on the author's list, of course.

**Comment by gdkrmr** [comment]
> Great! Should probably go ahead and update the URL in melpa and in places like the LanguageServer.jl wiki just to be safe.

I can do that.

**Comment by non-Jedi** [comment]
> Should I also remove you from the maintainers list?

I don't mind one way or the other. Like I said, I'm very unlikely to become active on this project again. I don't think the list of maintainers is publicly visible, so it doesn't matter at all in that respect.

**Comment by gdkrmr** [comment]
the .el file lists maintainers and authors

**Comment by non-Jedi** [comment]
Ah. Ya. Take me off that please. Thought you were talking about gh commit rights.
