### ISSUE TITLE
melpa release

### ISSUE THREAD

**Issue by gdkrmr** [gdkrmr/lsp-julia#6]
A release on melpa would be great!

**Comment by tpapp** [comment]
I have done it for `julia-repl`, and found it fairly easy. A [single file recipe](https://github.com/melpa/melpa#example-single-file-repository) would be enough for this package, further requirements are [here](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org). You also get a code review from very experienced Emacs programmers.

**Comment by gdkrmr** [comment]
It is pretty simple, here is how I did it for `flycheck-julia`: https://github.com/melpa/melpa/pull/4817
