### ISSUE TITLE
Missing reference of functions

### ISSUE THREAD

**Issue by roiholtzman** [gdkrmr/lsp-julia#60]
I am running `lsp-julia` on `doom-emacs`.
My problem is that when I call a function, say `foo`, that is defined in another file, I get a `Missing reference: foo` warning. 

How can make sure such functions are identified?

**Comment by gdkrmr** [comment]
That looks like a LanguageServer.jl problem, not sure if we can do anything about this at the Emacs level.

**Comment by roiholtzman** [comment]
thanks @gdkrmr. I have mentioned my problem in this [issue](https://github.com/julia-vscode/LanguageServer.jl/issues/391).
