### ISSUE TITLE
Julia environments

### ISSUE THREAD

**Issue by warnerwarner** [gdkrmr/lsp-julia#67]
Hi,

I'm sure I'm just missing something obvious, but is there a way to use a specific environment of Julia on a per project basis? I can get it to work with the `(setq lsp-julia-default-environment "~/.julia/environments/v1.7"))` line, but a lot of my work centers around different environments for different projects. Aside from editing the default environment when I switch, is there a way to assign a specific environment to a specific project?

Thanks

**Comment by gdkrmr** [comment]
The environment should be chosen automatically from the file (https://github.com/gdkrmr/lsp-julia/blob/c869b2f6c05a97e5495ed3cc6710a33b4faf41a2/lsp-julia.el#L250-L257), only if the file is not part of a project, `lsp-julia-default-environment` is used. So this path should be updated accordingly in your config.
