### ISSUE TITLE
Include ess-julia-mode in the list of major modes

### ISSUE THREAD

**Issue by csantosb** [gdkrmr/lsp-julia#8]
Hi

I'm using ess to deal with julia code: ess-julia-mode is the major mode of the buffer, so in order to enable lsp-julia it is necessary to include it along with julia-mode in the list of major modes.

Thanks

**Comment by prassee** [comment]
does this mean julia-mode.el should have a transitive dependency on ess-julia-mode or the other way around.

**Comment by csantosb** [comment]
Well, ess-julia.el requires julia-mode.el. But you may use julia-mode.el without ess-julia.
In case you decide to go with ess-julia, the major mode will be ess-julia-mode, and so this issue.
